"""add avatar_raw

Revision ID: 2a100ecebb95
Revises: c1c911f07247
Create Date: 2019-08-26 10:53:25.845816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a100ecebb95'
down_revision = 'c1c911f07247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_raw', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_raw')
    # ### end Alembic commands ###
