"""add fans follows

Revision ID: 924752291314
Revises: e023bf388b27
Create Date: 2019-08-14 09:40:03.706787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924752291314'
down_revision = 'e023bf388b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fan_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    op.drop_table('fans')
    # ### end Alembic commands ###
