"""add avatar size

Revision ID: a0dfc1b0c37b
Revises: 2a100ecebb95
Create Date: 2019-08-26 17:19:07.445001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0dfc1b0c37b'
down_revision = '2a100ecebb95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_l', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('avatar_m', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('avatar_s', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_s')
    op.drop_column('user', 'avatar_m')
    op.drop_column('user', 'avatar_l')
    # ### end Alembic commands ###
